import { link } from "fs";

export const siteConfig = {
  name: "Yushaku blog",
  url: "https://hookcn.ouassim.tech",
  ogImage: "https://hookcn.ouassim.tech/og.png",
  description: "Generated by create next app",
  links: {
    linkedin: "https://www.linkedin.com/in/levanson180200",
    twitter: "",
    github: "https://github.com/yushaku",
  },
};

export type SiteConfig = typeof siteConfig;

export const META_THEME_COLORS = {
  light: "#ffffff",
  dark: "#09090b",
};
